### ISSUE TITLE
Add more info about hactoberfest in readme.md

### ISSUE THREAD

**Issue by rhvsingh** [rhvsingh/hacktoberfest#12]
Add more info about hactoberfest in the readme.md
fix other details and make it look more eye appealing

**Comment by yogesh-9999** [comment]
hey @rhvsingh please assign this task to me

**Comment by rhvsingh** [comment]
> hey @rhvsingh please assign this task to me

Yeah sure @yogesh-9999

**Comment by rhvsingh** [comment]
@yogesh-9999 Nice work
