### ISSUE TITLE
Add Hacktoberfest logo in html webpage

### ISSUE THREAD

**Issue by rhvsingh** [rhvsingh/hacktoberfest#3]

**Comment by danschenker** [comment]
Once the site is built, I'd love to give this a try if it's alright with you @rhvsingh

**Comment by rhvsingh** [comment]
@danschenker sure, good to go now

**Comment by danschenker** [comment]
Thanks @rhvsingh! I was able to get the logo situated, but when I try to publish, I'm getting a permission denied error on [this repo](https://github.com/rhvsingh/website_repo_2). Would you mind giving me access, please? Or am I in the wrong place? Thanks!

**Comment by rhvsingh** [comment]
> Thanks @rhvsingh! I was able to get the logo situated, but when I try to publish, I'm getting a permission denied error on [this repo](https://github.com/rhvsingh/website_repo_2). Would you mind giving me access, please? Or am I in the wrong place? Thanks!

Send PR, the first fork then sends PR
If you are trying to push it directly then this will be the error you are getting. So first you have to fork it, then from that make changes locally, push it in your repo and then send PR.

**Comment by danschenker** [comment]
> > Thanks @rhvsingh! I was able to get the logo situated, but when I try to publish, I'm getting a permission denied error on [this repo](https://github.com/rhvsingh/website_repo_2). Would you mind giving me access, please? Or am I in the wrong place? Thanks!
> 
> 
> 
> Send PR, the first fork then sends PR
> 
> If you are trying to push it directly then this will be the error you are getting. So first you have to fork it, then from that make changes locally, push it in your repo and then send PR.

Ah right, thanks for being kind about this! I have it forked and saved locally, but I tried to publish it thinking that it would make a PR automatically.

I'm away from my computer, but I'll try again soon!

**Comment by rhvsingh** [comment]
> > > Thanks @rhvsingh! I was able to get the logo situated, but when I try to publish, I'm getting a permission denied error on [this repo](https://github.com/rhvsingh/website_repo_2). Would you mind giving me access, please? Or am I in the wrong place? Thanks!
> > 
> > 
> > Send PR, the first fork then sends PR
> > If you are trying to push it directly then this will be the error you are getting. So first you have to fork it, then from that make changes locally, push it in your repo and then send PR.
> 
> Ah right, thanks for being kind about this! I have it forked and saved locally, but I tried to publish it thinking that it would make a PR automatically.
> 
> I'm away from my computer, but I'll try again soon!

As far as I know that for the first time you have to do PR manually after that, it will be published automatically.

**Comment by danschenker** [comment]
Alright, I think I got it 😅 More power to you for opening up issues for newbies like myself. It's really kind of you!

**Comment by yogesh-9999** [comment]
hey @danschenker  assign this task to me

**Comment by rhvsingh** [comment]
> hey @danschenker assign this task to me

Sorry, I forgot to close this issue. You can look for other issues.
