### ISSUE TITLE
Update website for Hacktoberfest 2023

### ISSUE THREAD

**Issue by rhvsingh** [rhvsingh/hacktoberfest#32]

**Comment by vivek-singh-13** [comment]
I can do this. What exactly do I need to update apart from changing the 2022 -> 2023, does the project links also need to be updated?

**Comment by HamnaJabbar** [comment]
Hi @rhvsingh !Could you explain what you want to update?

**Comment by shu-qian** [comment]
hello,I want to do it!

**Comment by shu-qian** [comment]
Please assign this issue to me @rhvsingh
